IZ-ZMZPKOD-42-formularz-logowania-wraz-z-wywolaniem-funkcji-logowania
ZwinneDreamTeam/zwinne pull request #20
Opened 2018-04-03 17:42 UTC by izzy6

- email, password fields
- login method
- register button - not working on this branch!

2018-04-03 18:16 UTC, AdaF567 approved these changes

2018-04-04 04:19 UTC, MarcinusX requested changes

2018-04-04 04:19 UTC, MarcinusX commented on src/components/Login.vue
> +    <md-card class="loginPanelView" style="padding : 10px;">
A może w cssach?

2018-04-04 14:03 UTC, izzy6 commented on src/components/Login.vue
> +    <md-card class="loginPanelView" style="padding : 10px;">
Ależ proszę, poprawiłam...

2018-04-04 19:32 UTC, Asasello reviewed
A jest szansa by dodać tu validacje mail'a i password'a?

2018-04-05 06:56 UTC, izzy6 commented
@Asasello, w mojej opinii nie ma to sensu. Przecież jeżeli user ma już konto, to jego dane przeszły walidację.... Chyba, że chodzi ci o wyświetlanie na czerwono ze dane są nieprowidłowe zamiast domyślego komunikatu

2018-04-05 09:34 UTC, Asasello approved these changes

2018-04-06 11:32 UTC, MarcinusX approved these changes
:)

2018-04-06 11:32 UTC, MarcinusX commented on src/components/Login.vue
> +      "confirm": "Confirm",
Confirm => Login? :)

2018-04-06 11:32 UTC, MarcinusX commented on src/components/Login.vue
> +      <router-link :to="{name: 'register'}">
Czy to powinno mnie przenosić do homa?

2018-04-06 11:33 UTC, merged