Iz zmzpkod 44 widok szczegolow wlasnego konta i edycja
ZwinneDreamTeam/zwinne pull request #21
Opened 2018-04-03 18:04 UTC by izzy6

+ naprawiony widok użytkownika - switche roli

2018-04-04 04:17 UTC, MarcinusX requested changes

2018-04-04 04:17 UTC, MarcinusX commented on src/components/UserDetails.vue
> +        console.log(key)
Usuń to :)

2018-04-04 04:17 UTC, MarcinusX commented on src/App.vue
> +  var currentUser
??

2018-04-04 04:17 UTC, MarcinusX commented on src/components/Home.vue
> +      users: usersRef
Do czego to potrzebne?

2018-04-04 04:17 UTC, MarcinusX commented on src/components/Home.vue
>  <template>
Wgl dlaczego ten link jest w Home zamiast pasku bocznym lub gornym?

2018-04-04 04:17 UTC, MarcinusX commented on src/router/index.js
> +      path: '/user/:id',
Dlaczego currentUserDetails potrzebuje id jako parametru???

2018-04-04 04:17 UTC, MarcinusX commented on src/components/UserDetails.vue
> +          //console.log(currentUser);
//po
//co
//zostawiac
//komentarze?

2018-04-04 11:00 UTC, izzy6 commented on src/components/UserDetails.vue
> +        console.log(key)
Usunięte

2018-04-04 11:01 UTC, izzy6 commented on src/App.vue
> +  var currentUser
Usunięte

2018-04-04 11:01 UTC, izzy6 commented on src/components/Home.vue
> +      users: usersRef
Usunięte

2018-04-04 11:01 UTC, izzy6 commented on src/components/Home.vue
>  <template>
Przeniesione do paska bocznego

2018-04-04 11:01 UTC, izzy6 commented on src/router/index.js
> +      path: '/user/:id',
Bo tak, tego nie zmienię

2018-04-04 11:02 UTC, izzy6 commented on src/components/AppDrawer.vue
>        console.log("mounted");
@MarcinusX a cóż to?? :P

2018-04-05 08:24 UTC, izzy6 commented
@MarcinusX, masz poprawiony język oraz sposób pobierania danych z bazy

2018-04-07 10:43 UTC, MarcinusX approved these changes
.

2018-04-07 10:53 UTC, Asasello approved these changes

2018-04-07 10:53 UTC, merged