download test in pdf format
ZwinneDreamTeam/zwinne pull request #39
Opened 2018-04-15 19:35 UTC by bartek221661

npm i jspdf --save

2018-04-17 09:53 UTC, Asasello approved these changes

2018-04-18 04:42 UTC, patryk-kacperski requested changes
Wszystkie testy -> Test super test -> język angielski
Nie da się pobrać pdfa

2018-04-18 07:09 UTC, bartek221661 commented
poprawione na branchu 59

2018-04-18 18:12 UTC, bartek221661 commented
@patryk-kacperski możesz teraz sprawdzić an branchu 58

2018-04-18 18:32 UTC, patryk-kacperski approved these changes
👍

2018-04-18 18:32 UTC, merged