Zmzpkod 54 zablokowanie printscreen
ZwinneDreamTeam/zwinne pull request #42
Opened 2018-04-17 09:16 UTC by Asasello

Blocking for mac.
Code refactor.

2018-04-17 09:53 UTC, barteksto approved these changes

2018-04-18 04:31 UTC, patryk-kacperski requested changes
Kiedy wcisnąłem cmd+shift+4, żeby zrobić print screena obraz w istocie się rozmazał, ale potem pozostał rozmazany, musiałem przeładować stronę aby znów był ostry

Za drugim razem udało się normalnie zrobić print screena. Blokowanie print screena nie działa po odświeżeniu strony

2018-04-18 07:04 UTC, Asasello commented
Teraz działa dla cmd+shift+3, dla cmd+shift+4 będzie dalej blur po zrobieniu ps, czego nie zmienię.

2018-04-18 18:35 UTC, patryk-kacperski approved these changes
👍

2018-04-18 18:35 UTC, merged