Zmzpkod 60 przechodzenie testu
ZwinneDreamTeam/zwinne pull request #44
Opened 2018-04-17 20:15 UTC by patryk-kacperski

2018-04-18 08:05 UTC, Asasello requested changes
Przy sliderze fajnie by było dodać min i max by user nie musiał sam scrollować do końca by sprawdzić zakres.
Przy odpowiedzi liczbowej nie ma wiadomości, że tylko liczby są akceptowane.

2018-04-18 19:00 UTC, patryk-kacperski commented
@Asasello done

2018-04-18 19:10 UTC, Asasello approved these changes

2018-04-19 08:36 UTC, AdaF567 approved these changes

2018-04-19 08:37 UTC, merged